# @package _global_

defaults:
  - _self_
  - data: default
  - policy: bc_transformer_policy
  - train: default
  - eval: default
  - lifelong: base
  - test: null

seed: 10000
use_wandb: false
wandb_project: "lifelong learning"
folder: "/home/lambs1031/SmolVLA_0812/LIBERO/libero/datasets" # 직접 경로 설정
bddl_folder: "/home/lambs1031/SmolVLA_0812/LIBERO/libero/libero/bddl_files" # 직접 경로 설정
init_states_folder: "/home/lambs1031/SmolVLA_0812/LIBERO/libero/libero/init_files" # 직접 경로 설정
load_previous_model: false
device: "cuda"
task_embedding_format: "bert"
task_embedding_one_hot_offset: 1
pretrain: false
pretrain_model_path: ""
benchmark_name: "LIBERO_SPATIAL"
